Exanimum18/paws-finder-914

app/controllers/posts_controller.rb
app/views/posts/index.html.erb
app/views/posts/new.html.erb
config/routes.rb

Comprobando fotos en el index de posts

Comprobando fotos en el index de posts

---

app/controllers/posts_controller.rb
app/models/animal.rb
app/models/post.rb
app/views/posts/edit.html.erb
app/views/posts/index.html.erb
app/views/posts/new.html.erb
app/views/posts/show.html.erb

Controlador de post casi listo

---

app/controllers/posts_controller.rb
app/models/animal.rb
app/views/posts/index.html.erb
app/views/posts/new.html.erb

Controlador de posts terminado

---

app/controllers/posts_controller.rb
app/controllers/reviews_controller.rb
app/views/layouts/application.html.erb
app/views/posts/show.html.erb
app/views/shared/_navbar.html.erb

Controlador de reviews casi terminado

---

app/controllers/posts_controller.rb
app/controllers/reviews_controller.rb
app/views/posts/show.html.erb

Solo falta una cosita

---

app/controllers/reviews_controller.rb
app/models/review.rb
app/models/user.rb
app/views/posts/show.html.erb
db/migrate/20221018010244_add_reference_to_reviews.rb
db/schema.rb
db/seeds.rb

Quedo listo el controlador de reviews

---

Gemfile
Gemfile.lock
app/controllers/posts_controller.rb
app/javascript/controllers/index.js
app/javascript/controllers/map_controller.js
app/models/animal.rb
app/models/post.rb
app/models/review.rb
app/models/user.rb
app/views/layouts/application.html.erb
app/views/posts/index.html.erb
app/views/posts/show.html.erb
test/models/animal_test.rb
test/models/post_test.rb
test/models/review_test.rb
test/models/user_test.rb

falta hacer que solo muestre el marker del post actual

map en show

---

app/controllers/posts_controller.rb
app/controllers/reviews_controller.rb
app/models/review.rb
app/views/posts/show.html.erb
app/views/reviews/edit.html.erb
config/routes.rb
db/seeds.rb

Por fin funcionando el controlador de reviewa

---

app/controllers/posts_controller.rb
app/views/layouts/application.html.erb
app/views/posts/mis_publicaciones.html.erb
config/routes.rb

Tus publicaciones

---

app/views/posts/mis_publicaciones.html.erb

Organizando la view de mis publicaciones

---

app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_signUp.scss
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_links.html.erb

login, sign in, forgot password, translate to spanish, fix footer, background images in pages, glass efect in forms

cambios omg

---

app/views/posts/new.html.erb
package.json
yarn.lock

Arreglado el error de los mapas

Arreglando problemas de mapas

---

app/controllers/posts_controller.rb
app/models/post.rb

El profesor Andrés evito que gastara todo el día en esto, xD

El search no funcionaba por que estaba comentado en el modelo de post

---

app/views/posts/mis_publicaciones.html.erb

Se agrego path de mis publicaciones al show

Se agrego path de mis publicaciones al show

---

app/assets/stylesheets/components/_chatroom.scss
app/assets/stylesheets/components/_index.scss
app/controllers/chatrooms_controller.rb
app/controllers/messages_controller.rb
app/models/chatroom.rb
app/models/message.rb
app/models/user.rb
app/views/chatrooms/show.html.erb
app/views/posts/show.html.erb
config/routes.rb
db/migrate/20221025215008_create_chatrooms.rb
db/migrate/20221025215028_create_messages.rb
db/schema.rb
test/controllers/chatrooms_controller_test.rb
test/controllers/messages_controller_test.rb
test/models/message_test.rb

Chat general listo

---

app/channels/chatroom_channel.rb
app/javascript/controllers/chatroom_subscription_controller.js
app/javascript/controllers/index.js
app/views/chatrooms/show.html.erb
package.json
test/channels/chatroom_channel_test.rb
yarn.lock

Avanzando en el chat

---

app/controllers/messages_controller.rb
app/javascript/controllers/chatroom_subscription_controller.js
app/views/chatrooms/show.html.erb
app/views/messages/_message.html.erb
config/cable.yml

El chat general quedo listo para funcionar en producción

Chat general terminado

---

Gemfile
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_message.scss
app/controllers/messages_controller.rb
app/javascript/controllers/chatroom_subscription_controller.js
app/models/message.rb
app/views/chatrooms/show.html.erb

Trabajando en el chatroom

---

app/controllers/messages_controller.rb
app/javascript/controllers/chatroom_subscription_controller.js
config/cable.yml

Ya esta funcionando el chat, se le agrega el CSS al enviar el mensaje

Chat general funcionando, falta montarlo a heroku

---

app/controllers/posts_controller.rb
app/javascript/controllers/map_controller.js

Se cambio la imagen de la ubicacion en el mapa para la publicacion que se muestra en el show

Configurando el mapa

---

app/controllers/posts_controller.rb
app/javascript/controllers/map_controller.js
app/views/posts/show.html.erb
app/views/shared/_navbar.html.erb

Se cambio el marker del mapa por el logo de la app

Agregado el logo al marker del mapa

---

app/controllers/posts_controller.rb
app/views/posts/index.html.erb
app/views/posts/new.html.erb

Ya se autocompleta el campo de post_type dependiendo del boton que opriman(Perdido o Encontrado)

Se arreglaron los botones de publicar mascota encontrada o perdida

---

app/assets/stylesheets/components/_avatar.scss
app/models/post.rb
app/views/posts/index.html.erb
app/views/posts/show.html.erb

validaciones de la foto, title, description

Se agregaron las validaciones de los posts

---

app/models/user.rb
app/views/messages/_message.html.erb
app/views/posts/show.html.erb

Se actualizo la seed del heroku

Heroku seed
